server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_auth?useSSL=false&serverTimezone=UTC
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

jwt:
  # En PROD cámbialo por una variable de entorno: JWT_SECRET
  secret: TuClaveSuperSecretaMuyLarga1234567890_ChangeMe_32chars_min
  access-expiration: 900000       # 15 minutos
  refresh-expiration: 604800000   # 7 días

# CORS sencillo para pruebas locales
cors:
  allowed-origins: "http://localhost:4200"
