spring:
  main:
    web-application-type: reactive  # <- asegura que quede vivo en modo WebFlux
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: producto-service
              uri: lb://producto-service
              predicates:
                - Path=/api/productos/**
                - Path=/api/categorias/**
            - id: pedido-service
              uri: lb://pedido-service
              predicates:
                - Path=/api/pedidos/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true