spring:
  application:
    name: pedido-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_pedido
    username: root
    password: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: mamanirafael324@gmail.com     # tu correo completo
    password: hhvk tzve okps shmq          # tu contraseña de aplicación (NO tu contraseña normal)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8183
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
app:
  mail:
    from: "MiTiendaRopa <mamanirafael324@gmail.com>"
  carrito:
    base-url: http://localhost:8185
  producto:
    base-url: http://localhost:8181
  auth:
    base-url: http://localhost:9000
logging:
  level:
    org.springframework.mail: DEBUG
    org.springframework.boot.autoconfigure.mail: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web: INFO
