spring:
  application:
    name: pedido-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_pedido
    username: root
    password: mysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8183
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
app:
  carrito:
    base-url: http://localhost:8185
  producto:
    base-url: http://localhost:8181
  auth:
    base-url: http://localhost:9000
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web: INFO
